spring:
  docker:
    compose:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
  #  autoconfigure:
#    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: admin
      password: admin
  h2:
    console:
      enabled: true
